[TOC]

------

<center><font size=7><b>JavaScript Promise</center></font></center>

---





## 回调

### 简介

JavaScript 主机（host）环境提供了许多函数，这些函数允许我们计划 **异步** 行为（action）—— 也就是在我们执行一段时间后才自行完成的行为。

- Javascript自带的回调函数
  1. **`setTimeout`**：用于在指定的时间后执行一个函数。
  2. **`setInterval`**：用于每隔一定时间重复执行一个函数。
  3. **事件处理器**：例如，`addEventListener` 方法用于响应用户的事件。
  4. **Promise**：Promise 对象的 `.then()` 方法接受一个回调函数，用于处理异步操作的成功结果。
  5. **Array 方法**：如 `forEach`、`map`、`filter` 等方法接收回调函数以对数组元素进行操作。



让我们看一下函数 `loadScript(src)`，该函数使用给定的 `src` 加载脚本：

```javascript
function loadScript(src) {
  // 创建一个 <script> 标签，并将其附加到页面
  // 这将使得具有给定 src 的脚本开始加载，并在加载完成后运行
  let script = document.createElement('script');
  script.src = src;
  document.head.append(script);
}
```

它将一个新的、带有给定 `src` 的、动态创建的标签 `<script src="…">` 插入到文档中。浏览器将自动开始加载它，并在加载完成后执行它。

我们可以像这样使用这个函数：

```javascript
// 在给定路径下加载并执行脚本
loadScript('/my/script.js');
```

脚本是“异步”调用的，因为它从现在开始加载，但是在这个加载函数执行完成后才运行。

如果在 `loadScript(…)` 下面有任何其他代码，它们不会等到脚本加载完成才执行。

假设我们需要在新脚本加载后立即使用它。它声明了新函数，我们想运行它们。

但如果我们在 `loadScript(…)` 调用后立即执行此操作，这将不会有效。

自然情况下，浏览器可能没有时间加载脚本。到目前为止，`loadScript` 函数并没有提供跟踪加载完成的方法。脚本加载并最终运行，仅此而已。但我们希望了解脚本何时加载完成，以使用其中的新函数和变量。



让我们添加一个 `callback` 函数作为 `loadScript` 的第二个参数，该函数应在脚本加载完成时执行：

```javascript
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(script);

  document.head.append(script);
}
```

`onload` 事件通常会在脚本加载和执行完成后执行一个函数。

现在，如果我们想调用该脚本中的新函数，我们应该将其写在回调函数中：

```javascript
loadScript('/my/script.js', function() {
  // 在脚本加载完成后，回调函数才会执行
  newFunction(); // 现在它工作了
  ...
});
```



这是我们的想法：第二个参数是一个函数（通常是匿名函数），该函数会在行为（action）完成时运行。

这被称为“基于回调”的异步编程风格。异步执行某项功能的函数应该提供一个 `callback` 参数用于在相应事件完成时调用。

> 这是一个带有真实脚本的可运行的示例：
>
> ```javascript
> function loadScript(src, callback) {
>   let script = document.createElement('script');
>   script.src = src;
>   script.onload = () => callback(script);
>   document.head.append(script);
> }
> 
> loadScript('https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.2.0/lodash.js', script => {
>   alert(`酷，脚本 ${script.src} 加载完成`);
>   alert( _ ); // _ 是所加载的脚本中声明的一个函数
> });
> ```



### 在回调中回调

依次加载多个脚本：多次嵌套

```js
loadScript('/my/script.js', function(script) {

  loadScript('/my/script2.js', function(script) {

    loadScript('/my/script3.js', function(script) {
      // ...加载完所有脚本后继续
    });

  });

});
```

在外部 `loadScript` 执行完成时，回调就会发起内部的 `loadScript`。

因此，每一个新行为（action）都在回调内部。这对于几个行为来说还好，但对于许多行为来说就不好了。



### 处理回调的 Error

这是 `loadScript` 的改进版本，可以跟踪加载错误：

```javascript
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`Script load error for ${src}`));

  document.head.append(script);
}
```

加载成功时，它会调用 `callback(null, script)`，否则调用 `callback(error)`。

用法：

```javascript
loadScript('/my/script.js', function(error, script) {
  if (error) {
    // 处理 error
  } else {
    // 脚本加载成功
  }
});
```

再次强调，我们在 `loadScript` 中所使用的方案其实很普遍。它被称为“Error 优先回调（error-first callback）”风格。

约定是：

1. `callback` 的第一个参数是为 error 而保留的。一旦出现 error，`callback(err)` 就会被调用。
2. 第二个参数（和下一个参数，如果需要的话）用于成功的结果。此时 `callback(null, result1, result2…)` 就会被调用。

因此，单一的 `callback` 函数可以同时具有报告 error 和传递返回结果的作用。



### 厄运金字塔

随着调用嵌套的增加，代码层次变得更深，维护难度也随之增加，尤其是我们使用的是可能包含了很多循环和条件语句的真实代码，而不是例子中的 `...`。

有时这些被称为“回调地狱”或“厄运金字塔”。





## Promise

### 基础语法

Promise 对象的构造器（constructor）语法如下：

```javascript
let promise = new Promise(function(resolve, reject) {
  // executor（代码，“制作者”）
});
```

传递给 `new Promise` 的函数被称为 **executor**。当 `new Promise` 被创建，executor 会自动运行。

参数 `resolve` 和 `reject` 是由 JavaScript 自身提供的回调。我们的代码仅在 executor 的内部。

当 executor 获得了结果，它应该调用以下回调之一：

- `resolve(value)` —— 如果任务成功完成并带有结果 `value`。
- `reject(error)` —— 如果出现了 error，`error` 即为 error 对象。

总结：executor 会自动运行并尝试执行一项工作。尝试结束后，如果成功则调用 `resolve`，如果出现 error 则调用 `reject`。

由 `new Promise` 构造器返回的 `promise` 对象具有以下内部属性：

- `state` —— 最初是 `"pending"`，然后在 `resolve` 被调用时变为 `"fulfilled"`，或者在 `reject` 被调用时变为 `"rejected"`。
- `result` —— 最初是 `undefined`，然后在 `resolve(value)` 被调用时变为 `value`，或者在 `reject(error)` 被调用时变为 `error`。

> 成功完成的例子
>
> ```js
> let promise = new Promise(function(resolve, reject) {
>   // 当 promise 被构造完成时，自动执行此函数
> 
>   // 1 秒后发出工作已经被完成的信号，并带有结果 "done"
>   setTimeout(() => resolve("done"), 1000);
> });
> ```
>
> 失败的例子
>
> ```js
> let promise = new Promise(function(resolve, reject) {
>   // 1 秒后发出工作已经被完成的信号，并带有 error
>   setTimeout(() => reject(new Error("Whoops!")), 1000);
> });
> ```



**`state` 和 `result` 都是内部的**

Promise 对象的 `state` 和 `result` 属性都是内部的。我们无法直接访问它们。但我们可以对它们使用 `.then`/`.catch`/`.finally` 方法。



#### then

语法如下：

```javascript
promise.then(
  function(result) { /* handle a successful result */ },
  function(error) { /* handle an error */ }
);
```

`.then` 的第一个参数是一个函数，该函数将在 promise resolved 且接收到结果后执行。

`.then` 的第二个参数也是一个函数，该函数将在 promise rejected 且接收到 error 信息后执行。

> 例如，以下是对成功 resolved 的 promise 做出的反应：
>
> ```javascript
> let promise = new Promise(function(resolve, reject) {
>   setTimeout(() => resolve("done!"), 1000);
> });
> 
> // resolve 运行 .then 中的第一个函数
> promise.then(
>   result => alert(result), // 1 秒后显示 "done!"
>   error => alert(error) // 不运行
> );
> ```
>
> 第一个函数被运行了。
>
> 在 reject 的情况下，运行第二个：
>
> ```javascript
> let promise = new Promise(function(resolve, reject) {
>   setTimeout(() => reject(new Error("Whoops!")), 1000);
> });
> 
> // reject 运行 .then 中的第二个函数
> promise.then(
>   result => alert(result), // 不运行
>   error => alert(error) // 1 秒后显示 "Error: Whoops!"
> );
> ```
>
> 如果我们只对成功完成的情况感兴趣，那么我们可以只为 `.then` 提供一个函数参数：
>
> ```javascript
> let promise = new Promise(resolve => {
>   setTimeout(() => resolve("done!"), 1000);
> });
> 
> promise.then(alert); // 1 秒后显示 "done!"
> ```



#### catch

如果我们只对 error 感兴趣，那么我们可以使用 `null` 作为第一个参数：`.then(null, errorHandlingFunction)`。或者我们也可以使用 `.catch(errorHandlingFunction)`，其实是一样的。

> ```javascript
> let promise = new Promise((resolve, reject) => {
>   setTimeout(() => reject(new Error("Whoops!")), 1000);
> });
> 
> // .catch(f) 与 promise.then(null, f) 一样
> promise.catch(alert); // 1 秒后显示 "Error: Whoops!"
> ```
>
> `.catch(f)` 调用是 `.then(null, f)` 的完全的模拟，它只是一个简写形式。



#### 清理：finally

就像常规 `try {...} catch {...}` 中的 `finally` 子句一样，promise 中也有 `finally`。

`finally` 的功能是设置一个处理程序在前面的操作完成后，执行清理/终结。

- `finally` 处理程序没有得到前一个处理程序的结果（它没有参数）。而这个结果被传递给了下一个合适的处理程序。
- 如果 `finally` 处理程序返回了一些内容，那么这些内容会被忽略。
- 当 `finally` 抛出 error 时，执行将转到最近的 error 的处理程序。

> 例如，停止加载指示器，关闭不再需要的连接等。
>
> 把它想象成派对的终结者。无论派对是好是坏，有多少朋友参加，我们都需要（或者至少应该）在它之后进行清理。
>
> 代码可能看起来像这样：
>
> ```javascript
> new Promise((resolve, reject) => {
>   /* 做一些需要时间的事，之后调用可能会 resolve 也可能会 reject */
> })
>   // 在 promise 为 settled 时运行，无论成功与否
>   .finally(() => stop loading indicator)
>   // 所以，加载指示器（loading indicator）始终会在我们继续之前停止
>   .then(result => show result, err => show error)
> ```

调用 `.finally(f)` 类似于 `.then(f, f)`，因为当 promise settled 时 `f` 就会执行：无论 promise 被 resolve 还是 reject。

请注意，`finally(f)` 并不完全是 `then(f,f)` 的别名。它们之间有重要的区别：

1. `finally` 处理程序（handler）没有参数。在 `finally` 中，我们不知道 promise 是否成功。我们的任务通常是执行“常规”的完成程序（finalizing procedures）。

2. `finally` 处理程序将结果或 error “传递”给下一个合适的处理程序。

   > 例如，在这结果被从 `finally` 传递给了 `then`：
   >
   > ```javascript
   > new Promise((resolve, reject) => {
   >   setTimeout(() => resolve("value"), 2000)
   > })
   >   .finally(() => alert("Promise ready")) // 先触发
   >   .then(result => alert(result)); // <-- .then 显示 "value"
   > ```
   >
   > 正如我们所看到的，第一个 promise 返回的 `value` 通过 `finally` 被传递给了下一个 `then`。

   这非常方便，因为 `finally` 并不意味着处理一个 promise 的结果。如前所述，无论结果是什么，它都是进行常规清理的地方。

   > 下面是一个 promise 返回结果为 error 的示例，让我们看看它是如何通过 `finally` 被传递给 `catch` 的：
   >
   > ```javascript
   > new Promise((resolve, reject) => {
   >   throw new Error("error");
   > })
   >   .finally(() => alert("Promise ready")) // 先触发
   >   .catch(err => alert(err));  // <-- .catch 显示这个 error
   > ```

   

3. `finally` 处理程序也不应该返回任何内容。如果它返回了，返回的值会默认被忽略。

   此规则的唯一例外是当 `finally` 处理程序抛出 error 时。此时这个 error（而不是任何之前的结果）会被转到下一个处理程序。



#### 使用then,cat示例：重写回调函数loadScript

我们从上一章获得了用于加载脚本的 `loadScript` 函数。

这是基于回调函数的变体：

```javascript
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`Script load error for ${src}`));

  document.head.append(script);
}
```

用 promise 重写它。

新函数 `loadScript` 将不需要回调。取而代之的是，它将创建并返回一个在加载完成时 resolve 的 promise 对象。外部代码可以使用 `.then` 向其添加处理程序（订阅函数）：

```javascript
function loadScript(src) {
  return new Promise(function(resolve, reject) {
    let script = document.createElement('script');
    script.src = src;

    script.onload = () => resolve(script);
    script.onerror = () => reject(new Error(`Script load error for ${src}`));

    document.head.append(script);
  });
}
```

用法：

```javascript
let promise = loadScript("https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js");

promise.then(
  script => alert(`${script.src} is loaded!`),
  error => alert(`Error: ${error.message}`)
);

promise.then(script => alert('Another handler...'));
```





### Promise 链

在 JavaScript 中，`.then(handler)` 中所使用的处理程序（handler）可以创建并返回一个 promise。在这种情况下，其他的处理程序将等待它 settled 后再获得其结果。

这是 Promise 设计的核心特性之一。

**新的 Promise 行为**

- **返回值**：当 `.then` 中的回调函数返回一个值，这个值会被包装成一个新的 Promise，并且在下一个 `.then` 中可以访问到。
- **处理异步操作**：如果回调函数返回一个 Promise，新的 Promise 会在这个 Promise 完成后再继续执行链中的下一个 `.then`。



结合以上知识，如果我们有一系列的异步任务要一个接一个地执行，我们可以创建一个 **promise 链**。

```javascript
new Promise(function(resolve, reject) {

  setTimeout(() => resolve(1), 1000); // (*)

}).then(function(result) { // (**)

  alert(result); // 1
  return result * 2;

}).then(function(result) { // (***)

  alert(result); // 2
  return result * 2;

}).then(function(result) {

  alert(result); // 4
  return result * 2;

});
```

它的想法是通过 `.then` 处理程序（handler）链进行传递 result。

运行流程如下：

1. 初始 promise 在 1 秒后 resolve `(*)`，
2. 然后 `.then` 处理程序被调用 `(**)`，它又创建了一个新的 promise（以 `2` 作为值 resolve）。
3. 下一个 `then` `(***)` 得到了前一个 `then` 的值，对该值进行处理（*2）并将其传递给下一个处理程序。
4. 依此类推。

随着 result 在处理程序链中传递，我们可以看到一系列的 `alert` 调用：`1` → `2` → `4`。

这样之所以是可行的，是因为每个对 `.then` 的调用都会返回了一个新的 promise，因此我们可以在其之上调用下一个 `.then`。

当处理程序返回一个值时，它将成为该 promise 的 result，所以将使用它调用下一个 `.then`。

> **新手常犯的一个经典错误：从技术上讲，我们也可以将多个 `.then` 添加到一个 promise 上。但这并不是 promise 链（chaining）。**
>
> 例如：
>
> ```javascript
> let promise = new Promise(function(resolve, reject) {
>   setTimeout(() => resolve(1), 1000);
> });
> 
> promise.then(function(result) {
>   alert(result); // 1
>   return result * 2;
> });
> 
> promise.then(function(result) {
>   alert(result); // 1
>   return result * 2;
> });
> 
> promise.then(function(result) {
>   alert(result); // 1
>   return result * 2;
> });
> ```
>
> 我们在这里所做的只是一个 promise 的几个处理程序。它们不会相互传递 result；相反，它们之间彼此独立运行处理任务。
>
> 在同一个 promise 上的所有 `.then` 获得的结果都相同 —— 该 promise 的结果。所以，在上面的代码中，所有 `alert` 都显示相同的内容：`1`。
>
> 实际上我们极少遇到一个 promise 需要多个处理程序的情况。使用链式调用的频率更高。





#### 示例：loadScript

与promise 化的 `loadScript` 结合使用，按顺序依次加载脚本：

```js
loadScript("/article/promise-chaining/one.js")
  .then(function(script) {
    return loadScript("/article/promise-chaining/two.js");
  })
  .then(function(script) {
    return loadScript("/article/promise-chaining/three.js");
  })
  .then(function(script) {
    // 使用在脚本中声明的函数
    // 以证明脚本确实被加载完成了
    one();
    two();
    three();
  });
```

我们可以用箭头函数来重写代码，让其变得简短一些：

```javascript
loadScript("/article/promise-chaining/one.js")
  .then(script => loadScript("/article/promise-chaining/two.js"))
  .then(script => loadScript("/article/promise-chaining/three.js"))
  .then(script => {
    // 脚本加载完成，我们可以在这儿使用脚本中声明的函数
    one();
    two();
    three();
  });
```

从技术上讲，我们可以向每个 `loadScript` 直接添加 `.then`，就像这样：

```javascript
loadScript("/article/promise-chaining/one.js").then(script1 => {
  loadScript("/article/promise-chaining/two.js").then(script2 => {
    loadScript("/article/promise-chaining/three.js").then(script3 => {
      // 此函数可以访问变量 script1，script2 和 script3
      one();
      two();
      three();
    });
  });
});
```

这段代码做了相同的事儿：按顺序加载 3 个脚本。但它是“向右增长”的。所以会有和使用回调函数一样的问题。

刚开始使用 promise 的人可能不知道 promise 链，所以他们就这样写了。通常，链式是首选。

有时候直接写 `.then` 也是可以的，因为嵌套的函数可以访问外部作用域。在上面的例子中，嵌套在最深层的那个回调（callback）可以访问所有变量 `script1`，`script2` 和 `script3`。但这是一个例外，而不是一条规则。



**Thenables**

确切地说，处理程序返回的不完全是一个 promise，而是返回的被称为 “thenable” 对象 —— 一个具有方法 `.then` 的任意对象。它会被当做一个 promise 来对待。

这个想法是，第三方库可以实现自己的“promise 兼容（promise-compatible）”对象。它们可以具有扩展的方法集，但也与原生的 promise 兼容，因为它们实现了 `.then` 方法。

这是一个 thenable 对象的示例：

```javascript
class Thenable {
  constructor(num) {
    this.num = num;
  }
  then(resolve, reject) {
    alert(resolve); // function() { native code }
    // 1 秒后使用 this.num*2 进行 resolve
    setTimeout(() => resolve(this.num * 2), 1000); // (**)
  }
}

new Promise(resolve => resolve(1))
  .then(result => {
    return new Thenable(result); // (*)
  })
  .then(alert); // 1000ms 后显示 2
```

JavaScript 检查在 `(*)` 行中由 `.then` 处理程序返回的对象：如果它具有名为 `then` 的可调用方法，那么它将调用该方法并提供原生的函数 `resolve` 和 `reject` 作为参数（类似于 executor），并等待直到其中一个函数被调用。在上面的示例中，`resolve(2)` 在 1 秒后被调用 `(**)`。然后，result 会被进一步沿着链向下传递。

这个特性允许我们将自定义的对象与 promise 链集成在一起，而不必继承自 `Promise`。



#### 更复杂的示例：fetch

在前端编程中，promise 通常被用于网络请求。

我们将使用 `fetch` 方法从远程服务器加载信息。

```js
let promise = fetch(url);
```

执行这条语句，向 `url` 发出网络请求并返回一个 promise。当远程服务器返回 header（是在 **全部响应加载完成前**）时，该 promise 使用一个 `response` 对象来进行 resolve。

为了读取完整的响应，我们应该调用 `response.text()` 方法：当全部文字内容从远程服务器下载完成后，它会返回一个 promise，该 promise 以刚刚下载完成的这个文本作为 result 进行 resolve。



下面这段代码向 `user.json` 发送请求，并从服务器加载该文本：

```javascript
fetch('/article/promise-chaining/user.json')
  // 当远程服务器响应时，下面的 .then 开始执行
  .then(function(response) {
    // 当 user.json 加载完成时，response.text() 会返回一个新的 promise
    // 该 promise 以加载的 user.json 为 result 进行 resolve
    return response.text();
  })
  .then(function(text) {
    // ……这是远程文件的内容
    alert(text); // {"name": "iliakan", "isAdmin": true}
  });
```

从 `fetch` 返回的 `response` 对象还包含 `response.json()` 方法，该方法可以读取远程数据并将其解析为 JSON。在我们的例子中，这更加方便，所以我们用这个方法吧。

为了简洁，我们还将使用箭头函数：

```javascript
// 同上，但使用 response.json() 将远程内容解析为 JSON
fetch('/article/promise-chaining/user.json')
  .then(response => response.json())
  .then(user => alert(user.name)); // iliakan，获取到了用户名
```

我们可以再向 GitHub 发送一个请求，加载用户个人资料并显示头像：

```javascript
// 发送一个对 user.json 的请求
fetch('/article/promise-chaining/user.json')
  // 将其加载为 JSON
  .then(response => response.json())
  // 发送一个到 GitHub 的请求
  .then(user => fetch(`https://api.github.com/users/${user.name}`))
  // 将响应加载为 JSON
  .then(response => response.json())
  // 显示头像图片（githubUser.avatar_url）3 秒（也可以加上动画效果）
  .then(githubUser => {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => img.remove(), 3000); // (*)
  });
```

为了使链可扩展，我们需要返回一个在头像显示结束时进行 resolve 的 promise。

```javascript
fetch('/article/promise-chaining/user.json')
  .then(response => response.json())
  .then(user => fetch(`https://api.github.com/users/${user.name}`))
  .then(response => response.json())
  .then(githubUser => new Promise(function(resolve, reject) { // (*)
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => {
      img.remove();
      resolve(githubUser); // (**)
    }, 3000);
  }))
  // 3 秒后触发
  .then(githubUser => alert(`Finished showing ${githubUser.name}`));
```

也就是说，第 `(*)` 行的 `.then` 处理程序现在返回一个 `new Promise`，只有在 `setTimeout` 中的 `resolve(githubUser)` `(**)` 被调用后才会变为 settled。链中的下一个 `.then` 将一直等待这一时刻的到来。

作为一个好的做法，异步行为应该始终返回一个 promise。这样就可以使得之后我们计划后续的行为成为可能。即使我们现在不打算对链进行扩展，但我们之后可能会需要。

最后，我们可以将代码拆分为可重用的函数：

```javascript
function loadJson(url) {
  return fetch(url)
    .then(response => response.json());
}

function loadGithubUser(name) {
  return loadJson(`https://api.github.com/users/${name}`);
}

function showAvatar(githubUser) {
  return new Promise(function(resolve, reject) {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => {
      img.remove();
      resolve(githubUser);
    }, 3000);
  });
}

// 使用它们：
loadJson('/article/promise-chaining/user.json')
  .then(user => loadGithubUser(user.name))
  .then(showAvatar)
  .then(githubUser => alert(`Finished showing ${githubUser.name}`));
  // ...
```





### promise 错误处理

promise 链在错误（error）处理中十分强大。当一个 promise 被 reject 时，控制权将移交至最近的 rejection 处理程序。这在实际开发中非常方便。

> 例如，下面代码中所 `fetch` 的 URL 是错的（没有这个网站），`.catch` 对这个 error 进行了处理：
>
> ```javascript
> fetch('https://no-such-server.blabla') // reject
>   .then(response => response.json())
>   .catch(err => alert(err)) // TypeError: Failed to fetch（这里的文字可能有所不同）
> ```
>
> 正如你所看到的，`.catch` 不必是立即的。它可能在一个或多个 `.then` 之后出现。
>
> 或者，可能该网站一切正常，但响应不是有效的 JSON。捕获所有 error 的最简单的方法是，将 `.catch` 附加到链的末尾：
>
> ```javascript
> fetch('/article/promise-chaining/user.json')
>   .then(response => response.json())
>   .then(user => fetch(`https://api.github.com/users/${user.name}`))
>   .then(response => response.json())
>   .then(githubUser => new Promise((resolve, reject) => {
>     let img = document.createElement('img');
>     img.src = githubUser.avatar_url;
>     img.className = "promise-avatar-example";
>     document.body.append(img);
> 
>     setTimeout(() => {
>       img.remove();
>       resolve(githubUser);
>     }, 3000);
>   }))
>   .catch(error => alert(error.message));
> ```
>
> 通常情况下，这样的 `.catch` 根本不会被触发。但是如果上述任意一个 promise rejected（网络问题或者无效的 json 或其他），`.catch` 就会捕获它。



#### 隐式 try…catch

promise 的执行者（executor）和 promise 的处理程序周围有一个“隐式的 `try..catch`”。如果发生异常，它就会被捕获，并被视为 rejection 进行处理。

> 例如，下面这段代码：
>
> ```javascript
> new Promise((resolve, reject) => {
>   throw new Error("Whoops!");
> }).catch(alert); // Error: Whoops!
> ```
>
> ……与下面这段代码工作上完全相同：
>
> ```javascript
> new Promise((resolve, reject) => {
>   reject(new Error("Whoops!"));
> }).catch(alert); // Error: Whoops!
> ```

在 executor 周围的“隐式 `try..catch`”自动捕获了 error，并将其变为 rejected promise。

这不仅仅发生在 executor 函数中，同样也发生在其处理程序中。如果我们在 `.then` 处理程序中 `throw`，这意味着 promise rejected，因此控制权移交至**最近的** error 处理程序。

最后的 `.catch` 不仅会捕获显式的 rejection，还会捕获它上面的处理程序中意外出现的 error。



#### 再次抛出（Rethrowing）

正如我们已经注意到的，链尾端的 `.catch` 的表现有点像 `try..catch`。我们可能有许多个 `.then` 处理程序，然后在尾端使用一个 `.catch` 处理上面的所有 error。

在常规的 `try..catch` 中，我们可以分析 error，如果我们无法处理它，可以将其再次抛出。对于 promise 来说，这也是可以的。

如果我们在 `.catch` 中 `throw`，那么控制权就会被移交到下一个最近的 error 处理程序。如果我们处理该 error 并正常完成，那么它将继续到最近的成功的 `.then` 处理程序。

`.catch` 块正常完成，下一个成功的 `.then` 处理程序就会被调用。

> 在下面的例子中，我们可以看到 `.catch` 的另一种情况。`(*)` 行的处理程序捕获了 error，但无法处理它（例如，它只知道如何处理 `URIError`），所以它将其再次抛出：
>
> ```javascript
> // 执行流：catch -> catch
> new Promise((resolve, reject) => {
> 
>   throw new Error("Whoops!");
> 
> }).catch(function(error) { // (*)
> 
>   if (error instanceof URIError) {
>     // 处理它
>   } else {
>     alert("Can't handle such error");
> 
>     throw error; // 再次抛出此 error 或另外一个 error，执行将跳转至下一个 catch
>   }
> 
> }).then(function() {
>   /* 不在这里运行 */
> }).catch(error => { // (**)
> 
>   alert(`The unknown error has occurred: ${error}`);
>   // 不会返回任何内容 => 执行正常进行
> 
> });
> ```
>
> 执行从第一个 `.catch` `(*)` 沿着链跳转至下一个 `(**)`。



#### 未处理的 rejection

如果出现 error，promise 的状态将变为 “rejected”，然后执行应该跳转至最近的 rejection 处理程序。

当发生一个常规的 error 并且未被 `try..catch` 捕获时，脚本会停止，并在控制台中留下了一个信息。对于在 promise 中未被处理的 rejection，也会发生类似的事。

JavaScript 引擎会跟踪此类 rejection，在这种情况下会生成一个全局的 error。

如果出现了一个 error，并且在这没有 `.catch`，那么 `unhandledrejection` 处理程序就会被触发，并获取具有 error 相关信息的 `event` 对象，所以我们就能做一些后续处理了。

通常此类 error 是无法恢复的，所以我们最好的解决方案是将问题告知用户，并且可以将事件报告给服务器。

在 Node.js 等非浏览器环境中，有其他用于跟踪未处理的 error 的方法。





### Promise API

在 `Promise` 类中，有 6 种静态方法。



#### Promise.all

假设我们希望并行执行多个 promise，并等待所有 promise 都准备就绪。可以使用`Promise.all`。

```js
let promise = Promise.all(iterable);
```

`Promise.all` 接受一个可迭代对象（通常是一个数组项为 promise 的数组），并返回一个新的 promise。

当所有给定的 promise 都 resolve 时，新的 promise 才会 resolve，并且其结果数组将成为新 promise 的结果。

请注意，结果数组中元素的顺序与其在源 promise 中的顺序相同。即使第一个 promise 花费了最长的时间才 resolve，但它仍是结果数组中的第一个。

> 例如，下面的 `Promise.all` 在 3 秒之后 settled，然后它的结果就是一个 `[1, 2, 3]` 数组：
>
> ```javascript
> Promise.all([
>   new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
>   new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
>   new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
> ]).then(alert); // 1,2,3 当上面这些 promise 准备好时：每个 promise 都贡献了数组中的一个元素
> ```

一个常见的技巧是，将一个任务数据数组映射（map）到一个 promise 数组，然后将其包装到 `Promise.all`。

> 例如，如果我们有一个存储 URL 的数组，我们可以像这样 fetch 它们：
>
> ```javascript
> let urls = [
>   'https://api.github.com/users/iliakan',
>   'https://api.github.com/users/remy',
>   'https://api.github.com/users/jeresig'
> ];
> 
> // 将每个 url 映射（map）到 fetch 的 promise 中
> let requests = urls.map(url => fetch(url));
> 
> // Promise.all 等待所有任务都 resolved
> Promise.all(requests)
>   .then(responses => responses.forEach(
>     response => alert(`${response.url}: ${response.status}`)
>   ));
> ```



如果任意一个 promise 被 reject，由 `Promise.all` 返回的 promise 就会立即 reject，并且带有的就是这个 error。

**如果出现 error，其他 promise 将被忽略**

`Promise.all` 没有采取任何措施来取消它们，因为 promise 中没有“取消”的概念。`AbortController`可以帮助我们解决 ，但它不是 Promise API 的一部分。



`Promise.all(iterable)` 允许在 `iterable` 中使用非 promise 的“常规”值

> 例如，这里的结果是 `[1, 2, 3]`：
>
> ```javascript
> Promise.all([
>   new Promise((resolve, reject) => {
>     setTimeout(() => resolve(1), 1000)
>   }),
>   2,
>   3
> ]).then(alert); // 1, 2, 3
> ```
>
> 所以我们可以在方便的地方将准备好的值传递给 `Promise.all`。



#### Promise.allSettled

**最近新增的特性**：这是一个最近添加到 JavaScript 的特性。 旧式浏览器可能需要 polyfills.



如果任意的 promise reject，则 `Promise.all` 整个将会 reject。当我们需要 **所有** 结果都成功时，它对这种“全有或全无”的情况很有用。如果其中一个请求失败，我们仍然对其他的感兴趣，可使用 `Promise.allSettled`。



`Promise.allSettled` 等待所有的 promise 都被 settle，无论结果如何。结果数组会是这样的：

- 对成功的响应，结果数组对应元素的内容为 `{status:"fulfilled", value:result}`，
- 对出现 error 的响应，结果数组对应元素的内容为 `{status:"rejected", reason:error}`。

> 例如，我们想要获取（fetch）多个用户的信息。
>
> ```javascript
> let urls = [
>   'https://api.github.com/users/iliakan',
>   'https://api.github.com/users/remy',
>   'https://no-such-url'
> ];
> 
> Promise.allSettled(urls.map(url => fetch(url)))
>   .then(results => { // (*)
>     results.forEach((result, num) => {
>       if (result.status == "fulfilled") {
>         alert(`${urls[num]}: ${result.value.status}`);
>       }
>       if (result.status == "rejected") {
>         alert(`${urls[num]}: ${result.reason}`);
>       }
>     });
>   });
> ```
>
> 上面的 `(*)` 行中的 `results` 将会是：
>
> ```javascript
> [
>   {status: 'fulfilled', value: ...response...},
>   {status: 'fulfilled', value: ...response...},
>   {status: 'rejected', reason: ...error object...}
> ]
> ```
>
> 所以，对于每个 promise，我们都得到了其状态（status）和 `value/reason`。



如果浏览器不支持 `Promise.allSettled`，很容易进行 polyfill：

```javascript
if (!Promise.allSettled) {
  const rejectHandler = reason => ({ status: 'rejected', reason });

  const resolveHandler = value => ({ status: 'fulfilled', value });

  Promise.allSettled = function (promises) {
    const convertedPromises = promises.map(p => Promise.resolve(p).then(resolveHandler, rejectHandler));
    return Promise.all(convertedPromises);
  };
}
```

在这段代码中，`promises.map` 获取输入值，并通过 `p => Promise.resolve(p)` 将输入值转换为 promise（以防传递了非 promise 值），然后向每一个 promise 都添加 `.then` 处理程序。

这个处理程序将成功的结果 `value` 转换为 `{status:'fulfilled', value}`，将 error `reason` 转换为 `{status:'rejected', reason}`。这正是 `Promise.allSettled` 的格式。

然后我们就可以使用 `Promise.allSettled` 来获取 **所有** 给定的 promise 的结果，即使其中一些被 reject。



#### Promise.race

与 `Promise.all` 类似，但只等待第一个 settled 的 promise 并获取其结果（或 error）。

```js
let promise = Promise.race(iterable);
```

> 例如，这里的结果将是 `1`：
>
> ```javascript
> Promise.race([
>   new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
>   new Promise((resolve, reject) => setTimeout(() => reject(new Error("Whoops!")), 2000)),
>   new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
> ]).then(alert); // 1
> ```
>
> 这里第一个 promise 最快，所以它变成了结果。第一个 settled 的 promise “赢得了比赛”之后，所有进一步的 result/error 都会被忽略。



#### Promise.any

例如，这里的结果将是 `1`：

```javascript
Promise.any([
  new Promise((resolve, reject) => setTimeout(() => reject(new Error("Whoops!")), 1000)),
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 2000)),
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
]).then(alert); // 1
```

这里的第一个 promise 是最快的，但 rejected 了，所以第二个 promise 则成为了结果。在第一个 fulfilled 的 promise “赢得比赛”后，所有进一步的结果都将被忽略。



#### Promise.resolve/reject

在现代的代码中，很少需要使用 `Promise.resolve` 和 `Promise.reject` 方法，因为 `async/await` 语法使它们变得有些过时了。

##### Promise.resolve

```javascript
let promise = new Promise(resolve => resolve(value));
```

当一个函数被期望返回一个 promise 时，这个方法用于兼容性。（译注：这里的兼容性是指，我们直接从缓存中获取了当前操作的结果 `value`，但是期望返回的是一个 promise，所以可以使用 `Promise.resolve(value)` 将 `value` “封装”进 promise，以满足期望返回一个 promise 的这个需求。）

> 例如，下面的 `loadCached` 函数获取（fetch）一个 URL 并记住其内容。以便将来对使用相同 URL 的调用，它能立即从缓存中获取先前的内容，但使用 `Promise.resolve` 创建了一个该内容的 promise，所以返回的值始终是一个 promise。
>
> ```javascript
> let cache = new Map();
> 
> function loadCached(url) {
>   if (cache.has(url)) {
>     return Promise.resolve(cache.get(url)); // (*)
>   }
> 
>   return fetch(url)
>     .then(response => response.text())
>     .then(text => {
>       cache.set(url,text);
>       return text;
>     });
> }
> ```
>
> 我们可以使用 `loadCached(url).then(…)`，因为该函数保证了会返回一个 promise。我们就可以放心地在 `loadCached` 后面使用 `.then`。这就是 `(*)` 行中 `Promise.resolve` 的目的。

##### Promise.reject

`Promise.reject(error)` 用 `error` 创建一个 rejected 的 promise。

```javascript
let promise = new Promise((resolve, reject) => reject(error));
```

实际上，这个方法几乎从未被使用过。





### Promisification

对于一个简单的转换来说 “Promisification” 是一个长单词。它指将一个接受回调的函数转换为一个返回 promise 的函数。

由于许多函数和库都是基于回调的，因此，在实际开发中经常会需要进行这种转换。因为使用 promise 更加方便，所以将基于回调的函数和库 promise 化是有意义的。



再次看回：回调函数`loadScript(src, callback)`。

这是基于回调函数的变体：

```javascript
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`Script load error for ${src}`));

  document.head.append(script);
}
// 用法：
// loadScript('path/script.js', (err, script) => {...})
```

之前第一次用 promise 重写它。

```javascript
function loadScript(src) {
  return new Promise(function(resolve, reject) {
    let script = document.createElement('script');
    script.src = src;

    script.onload = () => resolve(script);
    script.onerror = () => reject(new Error(`Script load error for ${src}`));

    document.head.append(script);
  });
}

// 用法：
// loadScriptPromise('path/script.js').then(...)
```

正如我们所看到的，新的函数是对原始的 `loadScript` 函数的包装。新函数调用它，并提供了自己的回调来将其转换成 promise `resolve/reject`。



在实际开发中，我们可能需要 promise 化很多函数，所以使用一个 helper（辅助函数）很有意义。

我们将其称为 `promisify(f)`：它接受一个需要被 promise 化的函数 `f`，并返回一个包装（wrapper）函数。

```javascript
function promisify(f) {
  return function (...args) { // 返回一个包装函数（wrapper-function） (*)
    return new Promise((resolve, reject) => {
      function callback(err, result) { // 我们对 f 的自定义的回调 (**)
        if (err) {
          reject(err);
        } else {
          resolve(result);
        }
      }

      args.push(callback); // 将我们的自定义的回调附加到 f 参数（arguments）的末尾

      f.call(this, ...args); // 调用原始的函数
    });
  };
}


// 用法：
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`Script load error for ${src}`));

  document.head.append(script);
}

let loadScriptPromise = promisify(loadScript);
loadScriptPromise(...).then(...);
```

代码看起来可能有些复杂，但其本质与我们在上面写的那个是一样的，就是将 `loadScript` 函数 promise 化。

一步一步分析这个 `promisify` 函数的实现和工作原理：

1. **函数返回包装器**：`promisify(f)` 接受一个函数 `f` 作为参数，并返回一个新的函数。这是通过 `return function (...args)` 实现的，这个新的函数可以接受任意数量的参数。
2. **创建 Promise**：在新的函数内部，返回一个 `Promise` 对象。`new Promise((resolve, reject) => {...})` 接受一个执行器函数，该函数内部会执行异步操作。
3. **定义回调函数**：在 `Promise` 内部，定义了一个 `callback(err, result)` 函数。这个回调函数用于处理 `f` 执行后的结果。如果 `err` 存在，调用 `reject(err)` 来拒绝 Promise；否则，调用 `resolve(result)` 来解决 Promise。
4. **附加回调**：使用 `args.push(callback)` 将自定义的回调函数添加到参数列表的末尾。这样，当原始函数 `f` 被调用时，它会收到这个回调作为参数。
5. **调用原始函数**：通过 `f.call(this, ...args)` 调用原始的函数 `f`，并传入修改后的参数列表。这里使用 `call` 方法确保 `this` 的上下文保持一致。
6. **处理结果**：当原始函数 `f` 执行完成时，它会调用传入的回调（即 `callback`），根据回调的参数决定是解决还是拒绝 Promise。

调用 `promisify(f)` 会返回一个 `f` `(*)` 的包装器。该包装器返回一个 promise，并将调用转发给原始的 `f`，并在我们自定义的回调 `(**)` 中跟踪结果。

在这里，`promisify` 假设原始函数期望一个带有两个参数 `(err, result)` 的回调。这就是我们最常遇到的形式。那么我们自定义的回调的格式是完全正确的，在这种情况下 `promisify` 也可以完美地运行。



但是如果原始的 `f` 期望一个带有更多参数的回调 `callback(err, res1, res2, ...)`，该怎么办呢？

我们可以继续改进我们的辅助函数。让我们写一个更高阶版本的 `promisify`。

- 当它被以 `promisify(f)` 的形式调用时，它应该以与上面那个版本的实现的工作方式类似。
- 当它被以 `promisify(f, true)` 的形式调用时，它应该返回以回调函数数组为结果 resolve 的 promise。这就是具有很多个参数的回调的结果。

```javascript
// promisify(f, true) 来获取结果数组
function promisify(f, manyArgs = false) {
  return function (...args) {
    return new Promise((resolve, reject) => {
      function callback(err, ...results) { // 我们自定义的 f 的回调
        if (err) {
          reject(err);
        } else {
          // 如果 manyArgs 被指定，则使用所有回调的结果 resolve
          resolve(manyArgs ? results : results[0]);
        }
      }

      args.push(callback);

      f.call(this, ...args);
    });
  };
}

// 用法：
f = promisify(f, true);
f(...).then(arrayOfResults => ..., err => ...);
```

正如你所看到的，它与上面那个实现基本相同，只是根据 `manyArgs` 是否为真来决定仅使用一个还是所有参数调用 `resolve`。

对于一些更奇特的回调格式，例如根本没有 `err` 的格式：`callback(result)`，我们可以手动 promise 化这样的函数，而不使用 helper。

也有一些具有更灵活一点的 promisification 函数的模块（module），例如 [es6-promisify](https://github.com/digitaldesignlabs/es6-promisify)。在 Node.js 中，有一个内建的 promise 化函数 `util.promisify`。



**Promisification 是一种很好的方法，但不是回调的完全替代。**

请记住，一个 promise 可能只有一个结果，但从技术上讲，一个回调可能被调用很多次。

因此，promisification 仅适用于调用一次回调的函数。进一步的调用将被忽略。





## 微任务（Microtask）

promise 的处理程序 `.then`、`.catch` 和 `.finally` 都是异步的。



### 微任务队列（Microtask queue）

异步任务需要适当的管理。为此，ECMA 标准规定了一个内部队列 `PromiseJobs`，通常被称为“微任务队列（microtask queue）”（V8 术语）。

如 [规范](https://tc39.github.io/ecma262/#sec-jobs-and-job-queues) 中所述：

- 队列（queue）是先进先出的：首先进入队列的任务会首先运行。
- 只有在 JavaScript 引擎中没有其它任务在运行时，才开始执行任务队列中的任务。

或者，简单地说，当一个 promise 准备就绪时，它的 `.then/catch/finally` 处理程序就会被放入队列中：但是它们不会立即被执行。当 JavaScript 引擎执行完当前的代码，它会从队列中获取任务并执行它。

> 即便一个 promise 立即被 resolve，`.then`、`.catch` 和 `.finally` **下面** 的代码也会在这些处理程序之前被执行。
>
> 示例代码如下：
>
> ```javascript
> let promise = Promise.resolve();
> 
> promise.then(() => alert("promise done!"));
> 
> alert("code finished"); // 这个 alert 先显示
> ```
>
> 如果你运行它，你会首先看到 `code finished`，然后才是 `promise done`。
>
> ![image-20240926174121642](https://raw.githubusercontent.com/Jenlybein/My-Typora-Images/imgs/202409261741866.png)

如果有一个包含多个 `.then/catch/finally` 的链，那么它们中的每一个都是异步执行的。也就是说，它会首先进入队列，然后在当前代码执行完成并且先前排队的处理程序都完成时才会被执行。

> **如果执行顺序对我们很重要该怎么办？我们怎么才能让 `code finished` 在 `promise done` 之后出现呢？**
>
> 很简单，只需要像下面这样使用 `.then` 将其放入队列：
>
> ```javascript
> Promise.resolve()
>   .then(() => alert("promise done!"))
>   .then(() => alert("code finished"));
> ```
>
> 现在代码就是按照预期执行的。





## async/await

async/await 是以更舒适的方式使用 promise 的一种特殊语法，同时它也非常易于理解和使用。



### async function

`async` 关键字可以被放置在一个函数前面。

`async` 确保了函数返回一个 promise，也会将非 promise 的值包装进去。

> 例如，下面这个函数返回一个结果为 `1` 的 resolved promise。
>
> ```javascript
> async function f() {
>   return 1;
> }
> 
> f().then(alert); // 1
> ```
>
> 也可以显式地返回一个 promise，结果是一样的：
>
> ```javascript
> async function f() {
>   return Promise.resolve(1);
> }
> 
> f().then(alert); // 1
> ```

在函数前面的 “async” 这个单词表达了一个简单的事情：即这个函数总是返回一个 promise。其他值将自动被包装在一个 resolved 的 promise 中。



### await

关键字 `await` 让 JavaScript 引擎等待直到 promise 完成（settle）并返回结果。

 `await` 关键词只在 `async` 函数内工作。

```js
let value = await promise;
```

> 这里的例子就是一个 1 秒后 resolve 的 promise：
>
> ```javascript
> async function f() {
> 
>   let promise = new Promise((resolve, reject) => {
>     setTimeout(() => resolve("done!"), 1000)
>   });
> 
>   let result = await promise; // 等待，直到 promise resolve (*)
> 
>   alert(result); // "done!"
> }
> 
> f();
> ```
>
> 这个函数在执行的时候，“暂停”在了 `(*)` 那一行，并在 promise settle 时，拿到 `result` 作为结果继续往下执行。所以上面这段代码在一秒后显示 “done!”。

`await` 实际上会暂停函数的执行，直到 promise 状态变为 settled，然后以 promise 的结果继续执行。这个行为不会耗费任何 CPU 资源，因为 JavaScript 引擎可以同时处理其他任务：执行其他脚本，处理事件等。

相比于 `promise.then`，它只是获取 promise 的结果的一个更优雅的语法。并且也更易于读写。

> 拿 **Promise 链** 章的 `showAvatar()` 例子，并将其改写成 `async/await` 的形式：
>
> 1. 我们需要用 `await` 替换掉 `.then` 的调用。
> 2. 另外，我们需要在函数前面加上 `async` 关键字，以使它们能工作。
>
> ```javascript
> async function showAvatar() {
> 
>   // 读取我们的 JSON
>   let response = await fetch('/article/promise-chaining/user.json');
>   let user = await response.json();
> 
>   // 读取 github 用户信息
>   let githubResponse = await fetch(`https://api.github.com/users/${user.name}`);
>   let githubUser = await githubResponse.json();
> 
>   // 显示头像
>   let img = document.createElement('img');
>   img.src = githubUser.avatar_url;
>   img.className = "promise-avatar-example";
>   document.body.append(img);
> 
>   // 等待 3 秒
>   await new Promise((resolve, reject) => setTimeout(resolve, 3000));
> 
>   img.remove();
> 
>   return githubUser;
> }
> 
> showAvatar();
> ```



**现代浏览器在 modules 里允许顶层的 `await`**

在现代浏览器中，当我们处于一个 module 中时，那么在顶层使用 `await` 也是被允许的。我们将在 [模块 (Module) 简介](https://zh.javascript.info/modules-intro) 中详细学习 modules。

例如：

```javascript
// 我们假设此代码在 module 中的顶层运行
let response = await fetch('/article/promise-chaining/user.json');
let user = await response.json();

console.log(user);
```

如果我们没有使用 modules，或者必须兼容 [旧版本浏览器](https://caniuse.com/mdn-javascript_operators_await_top_level) ，那么这儿还有一个通用的方法：包装到匿名的异步函数中。

像这样：

```javascript
(async () => {
  let response = await fetch('/article/promise-chaining/user.json');
  let user = await response.json();
  ...
})();
```



**`await` 接受 “thenables”**

像 `promise.then` 那样，`await` 允许我们使用 thenable 对象（那些具有可调用的 `then` 方法的对象）。这里的想法是，第三方对象可能不是一个 promise，但却是 promise 兼容的：如果这些对象支持 `.then`，那么就可以对它们使用 `await`。

> 这有一个用于演示的 `Thenable` 类，下面的 `await` 接受了该类的实例：
>
> ```javascript
> class Thenable {
>   constructor(num) {
>     this.num = num;
>   }
>   then(resolve, reject) {
>     alert(resolve);
>     // 1000ms 后使用 this.num*2 进行 resolve
>     setTimeout(() => resolve(this.num * 2), 1000); // (*)
>   }
> }
> 
> async function f() {
>   // 等待 1 秒，之后 result 变为 2
>   let result = await new Thenable(1);
>   alert(result);
> }
> 
> f();
> ```
>
> 如果 `await` 接收了一个非 promise 的但是提供了 `.then` 方法的对象，它就会调用这个 `.then` 方法，并将内建的函数 `resolve` 和 `reject` 作为参数传入（就像它对待一个常规的 `Promise` executor 时一样）。然后 `await` 等待直到这两个函数中的某个被调用（在上面这个例子中发生在 `(*)` 行），然后使用得到的结果继续执行后续任务。



**Class 中的 async 方法**

要声明一个 class 中的 async 方法，只需在对应方法前面加上 `async` 即可。

> 
>
> ```javascript
> class Waiter {
>   async wait() {
>     return await Promise.resolve(1);
>   }
> }
> 
> new Waiter()
>   .wait()
>   .then(alert); // 1（alert 等同于 result => alert(result)）
> ```
>
> 这里的含义是一样的：它确保了方法的返回值是一个 promise 并且可以在方法中使用 `await`。





### Error 处理

如果一个 promise 正常 resolve，`await promise` 返回的就是其结果。但是如果 promise 被 reject，它将 throw 这个 error，就像在这一行有一个 `throw` 语句那样。

> 这个代码：
>
> ```javascript
> async function f() {
>   await Promise.reject(new Error("Whoops!"));
> }
> ```
>
> 和下面是一样的：
>
> ```js
> async function f() {
>   throw new Error("Whoops!");
> }
> ```

在真实开发中，promise 可能需要一点时间后才 reject。在这种情况下，在 `await` 抛出（throw）一个 error 之前会有一个延时。

我们可以用 `try..catch` 来捕获上面提到的那个 error，与常规的 `throw` 使用的是一样的方式：

```javascript
async function f() {

  try {
    let response = await fetch('http://no-such-url');
  } catch(err) {
    alert(err); // TypeError: failed to fetch
  }
}

f();
```

如果有 error 发生，执行控制权马上就会被移交至 `catch` 块。我们也可以用 `try` 包装多行 `await` 代码：

```javascript
async function f() {

  try {
    let response = await fetch('/no-user-here');
    let user = await response.json();
  } catch(err) {
    // 捕获到 fetch 和 response.json 中的错误
    alert(err);
  }
}

f();
```

如果我们没有 `try..catch`，那么由异步函数 `f()` 的调用生成的 promise 将变为 rejected。我们可以在函数调用后面添加 `.catch` 来处理这个 error：

```javascript
async function f() {
  let response = await fetch('http://no-such-url');
}

// f() 变成了一个 rejected 的 promise
f().catch(alert); // TypeError: failed to fetch // (*)
```

如果我们忘了在这添加 `.catch`，那么我们就会得到一个未处理的 promise error（可以在控制台中查看）。我们可以使用全局事件处理程序 `unhandledrejection`(章：promise错误处理  有讲) 来捕获这类 error。



#### async/await 和 promise.then/catch

当我们使用 `async/await` 时，几乎就不会用到 `.then` 了，因为 `await` 为我们处理了等待。并且我们使用常规的 `try..catch` 而不是 `.catch`。这通常（但不总是）更加方便。

但是当我们在代码的顶层时，也就是在所有 `async` 函数之外，我们在语法上就不能使用 `await` 了，所以这时候通常的做法是添加 `.then/catch` 来处理最终的结果（result）或掉出来的（falling-through）error，例如像上面那个例子中的 `(*)` 行那样。



#### async/await 可以和 Promise.all 一起使用

当我们需要同时等待多个 promise 时，我们可以用 `Promise.all` 把它们包装起来，然后使用 `await`：

```javascript
// 等待结果数组
let results = await Promise.all([
  fetch(url1),
  fetch(url2),
  ...
]);
```

如果出现 error，也会正常传递，从失败了的 promise 传到 `Promise.all`，然后变成我们能通过使用 `try..catch` 在调用周围捕获到的异常（exception）。
